### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by adnanalahdab** [jondidating/genericTokenWatcher#1]
hi
this is not really an issue but i just needed help to start this up. I dont really know how to code but want to set this up. I downloaded the zipfile but now i dont know what to do. Could you please help me

**Comment by jondoescoding** [comment]
As much as I appreciate the enthusiasm for you wanting to set this up I can't simply just show you how to do that. Since you don't know how to code at all how do you know that this isn't a honeytrap setup to steal your tokens/information? 

With that I'd highly recommend you two paths:
1. Become a member of the [Degen code substack](degencode.substack.com) and learn from there
2. Take a look at the Automate the boring stuff tutorial and navigate from there
